### ISSUE TITLE
relativní vlhkost ODA, EHA

### ISSUE THREAD

**Issue by RemakTeam** [Remak-a-s/EC_Lot6_ComfTool#10]
přidej prosím bezpečné hodnoty relativních vlhkostí do wiki. 
Ď :-)

**Comment by ZhukovGreen** [comment]
I am sorry, but i didn't get which RH do you mean? I consider you mentioned RH for ref.unit, but what do you want to add else than ODA <any value> and ETA 0 + comment "If selection software doesn't allow enter RH0 to ETA parameters, you could increase to any value which respect the condition to have dry process of heat extracting from ETA (no condensation)"
